#!/usr/bin/env python3
"""
Pick the 20 question smoke set. See bench/METHOD.md.

Proportional sampling across the nine groups, with four slots reserved first for the shapes
that catch regressions rather than the ones that measure quality:

  a group G trap                  we most want to know if it has started inventing again
  a Blueprint blast radius        the one answer no C++ tool can reach
  a group F negation              an incorrect "no" is the failure that reads as a success
  a zero tool call group I        if Layer 4 stops being read, everything above it gets slower

The rest is filled proportionally. Seeded, so re-running gives the same set.

Usage:
  python make_smoke.py --root . --seed 3 --out bench/smoke-20.md
"""
import argparse, collections, json, os, random

# The hand written groups live in markdown, not JSON, so their pools are the ID ranges.
HAND = {'D': ['D%d' % i for i in range(1, 16)],
        'G': ['G%d' % i for i in range(1, 11)],
        'I': ['I%d' % i for i in range(1, 31)]}
HAND_FILE = 'bench/questions-handwritten.md'
GEN_FILE  = 'bench/questions-160.md'
ZERO_CALL = ['I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8']

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default='.')
    ap.add_argument('--questions', default='bench/questions-160.json')
    ap.add_argument('--seed', type=int, default=3)
    ap.add_argument('--out', default='bench/smoke-20.md')
    a = ap.parse_args()
    rng = random.Random(a.seed)

    gen = json.load(open(os.path.join(a.root, a.questions), encoding='utf-8'))['questions']
    by_group = collections.defaultdict(list)
    for q in gen: by_group[q['group']].append(q)

    picked, used = [], set()
    def take(q, why):
        key = q['id'] if isinstance(q, dict) else q
        if key in used: return False
        used.add(key); picked.append((q, why)); return True

    # Reserved slots first.
    take(rng.choice(HAND['G']), 'trap: has it started inventing again')
    blast = [q for q in by_group['E'] if q['shape'] == 'blueprint blast radius']
    if blast: take(rng.choice(blast), 'blast radius: the answer no C++ tool can reach')
    neg = [q for q in by_group['F'] if q['shape'] in ('no replication', 'no Blueprint caller')]
    if neg: take(rng.choice(neg), 'negation: a wrong "no" reads as a success')
    take(rng.choice(ZERO_CALL), 'Layer 4: should cost zero tool calls')

    # Then proportional, over what is left.
    sizes = {'A': 20, 'B': 20, 'C': 20, 'D': 15, 'E': 20, 'F': 15, 'G': 10, 'H': 10, 'I': 30}
    order = sorted(sizes, key=lambda g: -sizes[g])
    while len(picked) < 20:
        progressed = False
        for g in order:
            if len(picked) >= 20: break
            have = sum(1 for q, _ in picked if (q['group'] if isinstance(q, dict) else q[0]) == g)
            if have >= max(1, round(20 * sizes[g] / 160)) + 1: continue
            pool = by_group.get(g) or HAND.get(g, [])
            cand = [q for q in pool if (q['id'] if isinstance(q, dict) else q) not in used]
            if cand and take(rng.choice(cand), 'proportional'): progressed = True
        if not progressed: break

    rows = []
    for q, why in picked:
        if isinstance(q, dict):
            rows.append((q['id'], q['group'], q['project'], q['shape'], GEN_FILE, why,
                         q['question']))
        else:
            rows.append((q, q[0], '-', 'hand written', HAND_FILE, why, ''))
    rows.sort(key=lambda r: (r[1], r[0]))

    L = ['# Smoke set: 20 questions', '',
         'Generated by `bench/tools/make_smoke.py`, seed **%d**. Re-run with the same seed to get '
         'the same set.' % a.seed, '',
         'Per bench/METHOD.md this is the tier we run on every config change, so it has to '
         'stay quick enough that we keep running it. Four slots are reserved for the shapes that '
         'catch regressions rather than the ones that measure quality; the other sixteen are '
         'proportional to the group sizes.', '',
         '**Note:** section 3 asks for the smoke set to stay under a couple of minutes of wall '
         'clock. That was optimistic. One question per fresh session is not negotiable (see '
         'bench/METHOD.md), so twenty sessions is the floor, and the honest target is "quick '
         'enough to run before lunch" rather than two minutes.', '',
         '| # | Group | Project | Shape | Why it is in the smoke set | Full text |',
         '|---|---|---|---|---|---|']
    for i, g, p, s, f, why, _ in rows:
        L.append('| %s | %s | %s | %s | %s | `%s` |' % (i, g, p, s, why, f))
    L += ['', 'Counts: ' + ', '.join('%s=%d' % (g, n) for g, n in
                                     sorted(collections.Counter(r[1] for r in rows).items())), '']
    body = '\n'.join(L) + '\n'
    out = os.path.join(a.root, a.out)
    with open(out, 'w', encoding='utf-8') as f: f.write(body)
    print('wrote %s with %d questions' % (out, len(rows)))
    for g, n in sorted(collections.Counter(r[1] for r in rows).items()):
        print('  %s %d' % (g, n))

if __name__ == '__main__':
    main()
