"""Summarise a run's JSONL into the per-group table bench/full-run-results.md wants.

Per BASELINE-ARM-SPEC.md section 4: per group, MEDIAN seconds and MEDIAN retrieval bytes; session
tokens as a mean with the floor beside it. Representative and coverage sets are never averaged
into one number, so groups are always reported separately.

Where a question was measured more than once, every measurement is kept and the group median is
taken over all of them - the spec says record all runs, not the good one.
"""
import argparse
import collections
import io
import json
import statistics as st

# The per-arm floor is a fact about the harness, recorded in each run's meta
# file. It is no longer subtracted from anything here: see the note on `turns` in run_bench.py
# for the measurement that killed `tokens_above_floor`. Turns is the cost metric now.
def turns_of(r):
    """Turns for one question, from the record or from the call count on an older run."""
    t = r.get("turns")
    return t if t is not None else (r.get("calls") or 0) + 1

GROUP_NAMES = {
    "J": "Performance: the static determinants of cost",
    "A": "Structure: definition sites, property types",
    "B": "Inheritance and ancestry",
    "C": "Reflection: specifiers, replication",
    "D": "Comments and documentation",
    "E": "Blueprint blast radius",
    "F": "Negation: absence of replication",
    "G": "Traps: non-existence and ambiguity",
    "H": "Engine API surface",
    "I": "Build, tooling and procedure",
}


def load(path):
    return [json.loads(l) for l in io.open(path, encoding="utf-8") if l.strip()]


def med(vals):
    vals = [v for v in vals if v is not None]
    return st.median(vals) if vals else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--arm", required=True)
    args = ap.parse_args()

    rows = load(args.results)
    counts = collections.Counter(r["id"] for r in rows)
    repeated = sum(1 for v in counts.values() if v > 1)

    by_group = collections.defaultdict(list)
    for r in rows:
        by_group[r["group"]].append(r)

    out = []
    out.append("# Baseline arm results: %s" % args.arm)
    out.append("")
    out.append("Generated by `bench/tools/summarise_run.py`. Regenerate rather than hand edit.")
    out.append("")
    out.append("- Questions: **%d** unique, **%d** measurements" % (len(counts), len(rows)))
    out.append("- Measured more than once: **%d**" % repeated)
    out.append("- Turns: **%s** total, median **%.0f** per question"
               % (format(sum(turns_of(r) for r in rows), ","), med([turns_of(r) for r in rows])))
    out.append("- Errors or timeouts: **%d**" % sum(1 for r in rows if r.get("is_error") or r.get("timed_out")))
    out.append("")
    out.append("## Per group")
    out.append("")
    out.append("| Group | What | n | Median s | Median turns | Median bytes | Mean tokens | Total turns |")
    out.append("|---|---|---|---|---|---|---|---|")
    for g in sorted(by_group):
        rs = by_group[g]
        toks = [r.get("tokens_total_in") or 0 for r in rs]
        out.append("| %s | %s | %d | %.1f | %.0f | %s | %s | %s |" % (
            g, GROUP_NAMES.get(g, ""), len(rs),
            med([r.get("wall_seconds") for r in rs]),
            med([turns_of(r) for r in rs]),
            format(int(med([r.get("retrieval_bytes") for r in rs])), ","),
            format(int(sum(toks) / len(toks)), ","),
            format(sum(turns_of(r) for r in rs), ",")))
    out.append("")

    allr = rows
    out.append("**Overall:** median %.1fs, median %.0f turns, median %s retrieval bytes, mean %s tokens, %s turns in total."
               % (med([r.get("wall_seconds") for r in allr]),
                  med([turns_of(r) for r in allr]),
                  format(int(med([r.get("retrieval_bytes") for r in allr])), ","),
                  format(int(sum(r.get("tokens_total_in") or 0 for r in allr) / len(allr)), ","),
                  format(sum(turns_of(r) for r in allr), ",")))
    out.append("")

    out.append("## Most expensive questions")
    out.append("")
    out.append("| id | Group | s | turns | bytes | tokens |")
    out.append("|---|---|---|---|---|---|")
    for r in sorted(allr, key=lambda r: -(r.get("wall_seconds") or 0))[:12]:
        out.append("| %s | %s | %.1f | %s | %s | %s |" % (
            r["id"], r["group"], r.get("wall_seconds") or 0, turns_of(r),
            format(r.get("retrieval_bytes") or 0, ","),
            format(r.get("tokens_total_in") or 0, ",")))
    out.append("")

    out.append("## Run-to-run spread, where a question was measured twice")
    out.append("")
    byid = collections.defaultdict(list)
    for r in allr:
        byid[r["id"]].append(r)
    pairs = [v for v in byid.values() if len(v) == 2]
    if pairs:
        def spread(a, b, f):
            x, y = a.get(f) or 0, b.get(f) or 0
            m = (x + y) / 2.0
            return abs(x - y) / m if m else 0.0
        out.append("| Field | Median relative spread |")
        out.append("|---|---|")
        for f in ("wall_seconds", "calls", "retrieval_bytes", "tokens_total_in"):
            out.append("| `%s` | %.1f%% |" % (f, 100 * st.median([spread(a, b, f) for a, b in pairs])))
        out.append("")
        out.append("Over %d questions measured twice. Single-run per-question figures should not be "
                   "read precisely; the group medians above are the unit that means something." % len(pairs))
    out.append("")

    out.append("## Per question")
    out.append("")
    out.append("| id | Group | Project | s | turns | calls | bytes | tokens |")
    out.append("|---|---|---|---|---|---|---|---|")
    for r in sorted(allr, key=lambda r: (r["group"], r["id"], r.get("recorded_at") or "")):
        out.append("| %s | %s | %s | %.1f | %s | %s | %s | %s |" % (
            r["id"], r["group"], r.get("project", "-"), r.get("wall_seconds") or 0,
            turns_of(r), r.get("calls"), format(r.get("retrieval_bytes") or 0, ","),
            format(r.get("tokens_total_in") or 0, ",")))
    out.append("")

    with io.open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote %s (%d lines)" % (args.out, len(out)))


if __name__ == "__main__":
    main()
