<#
    PreToolUse. Refuses to let a generated file be hand-edited, whether the edit comes through Write,
    Edit, or a shell command.

    The artefacts under Docs/AgentMemory are written by a commandlet that walks the live reflection
    system, and the next dump overwrites the lot. So an edit to one is not a change, it is a change that
    will be silently reverted - and in the meantime the file says something the code does not. Same for
    the install record, which exists so a later check can tell which plugin version a project came from.

    **Why this also watches Bash, despite the cost.** The first version matched Write and Edit only. That
    guard was bypassed the first time anybody tested it, by a session whose configuration told it to make
    file changes with sed and heredocs: a `sed -i` on an artefact went straight past it and nothing said
    a word. A guard that covers only the paths nobody takes is worse than no guard, because it produces
    confidence rather than protection. Shell writes are the normal path in plenty of sessions, so they
    are covered here and the extra ~220ms per Bash call is the price.

    Reads the hook payload on stdin: tool_name, tool_input.file_path, tool_input.command. Emits a deny
    decision with a reason, which the model sees, so it can do the right thing instead of retrying.

    **It fails open, deliberately and in every direction.** Unreadable payload, unrecognised tool, a
    command it cannot parse: exit 0 and say nothing. It also only denies a shell command when it can see
    both a protected path and something that writes to it, so reading, grepping and copying an artefact
    somewhere else all pass. A guard that blocks work it did not understand gets removed, and then so
    does the protection.
#>
$ErrorActionPreference = 'Stop'

try {
    $raw = [Console]::In.ReadToEnd()
    if (-not $raw) { exit 0 }
    $payload = $raw | ConvertFrom-Json
}
catch { exit 0 }

# What is generated, and what to do instead. One place, because two lists drift.
$Protected = @(
    @{ Name    = 'a reflection artefact'
       Path    = 'Docs[/\\]AgentMemory[/\\]'
       Because = ('It is generated by the AgentMemoryDump commandlet, and the next dump overwrites it. ' +
                  'Editing it changes nothing durable and makes the artefact disagree with the code until ' +
                  'then. If the content is wrong, fix the source or the commandlet and regenerate with ' +
                  '/ue-memory-stack:update. If you need a note that survives, put it in a design doc.') }
    @{ Name    = 'the install record'
       Path    = '\.claude[/\\]\.uea-install\.json'
       Because = ('It is generated by the setup script and is how a later check tells which plugin version ' +
                  'this project came from. Hand-editing it makes that check lie. Re-run ' +
                  '/ue-memory-stack:setup instead.') }
)

function Deny([string] $Reason) {
    @{
        hookSpecificOutput = @{
            hookEventName            = 'PreToolUse'
            permissionDecision       = 'deny'
            permissionDecisionReason = $Reason
        }
    } | ConvertTo-Json -Depth 4 -Compress
    exit 0
}

$tool = $payload.tool_name

# --- Write and Edit: the file path is handed to us -------------------------------------------------
if ($tool -in 'Write', 'Edit', 'MultiEdit', 'NotebookEdit') {
    $path = $null
    if ($payload.tool_input) { $path = $payload.tool_input.file_path }
    if (-not $path) { exit 0 }
    foreach ($p in $Protected) {
        if ($path -match $p.Path) { Deny "$($path) is $($p.Name). $($p.Because)" }
    }
    exit 0
}

# --- Bash: the file path is somewhere in a command line -------------------------------------------
if ($tool -eq 'Bash') {
    $command = $null
    if ($payload.tool_input) { $command = $payload.tool_input.command }
    if (-not $command) { exit 0 }

    foreach ($p in $Protected) {
        if ($command -notmatch $p.Path) { continue }

        # A protected path appears. Now: does this command write to it, or only read it? Each pattern
        # below ties a writing verb to the protected path rather than matching the verb anywhere, so
        # `grep COND Docs/AgentMemory/... > /tmp/out` and `cp Docs/AgentMemory/x.md /tmp/` both pass.
        $path = $p.Path
        $writes = @(
            # In-place editors take their target as an argument, so the path appearing at all is enough.
            "sed\s+(-\S+\s+)*-\S*i\S*\b[^|;&]*$path"
            "perl\s+-\S*i\S*\b[^|;&]*$path"
            "awk\s+-i\s+inplace[^|;&]*$path"
            # Redirection and tee, where the target follows the operator.
            ">>?\s*[""']?[^""'\s|;&]*$path"
            "\btee\b\s+(-a\s+)?[""']?[^""'\s|;&]*$path"
            # PowerShell's writers, which take the path as a parameter or by pipeline.
            "(Set-Content|Add-Content|Out-File|Set-ItemProperty|New-Item)[^|;&]*$path"
            # Copy, move and delete, where the protected path is the destination or the victim.
            "(\bcp\b|\bmv\b|Copy-Item|Move-Item)[^|;&]*$path[^\s|;&]*\s*($|[|;&])"
            "(\brm\b|\bdel\b|Remove-Item|\btruncate\b|\bshred\b)[^|;&]*$path"
            # A heredoc or a pipe into a writer.
            "cat\s*<<[^|;&]*>\s*[""']?[^""'\s|;&]*$path"
        ) -join '|'

        if ($command -match $writes) {
            Deny ("That shell command writes to $($p.Name) ($($command.Trim())). $($p.Because) " +
                  'Reading it, grepping it or copying it elsewhere is fine; changing it in place is not.')
        }
    }
    exit 0
}

exit 0
