<#
    PostToolUse on Bash. After a command that built something, says once that the artefacts are now
    behind the binaries.

    The order this stack needs is build, then dump. The failure it produces when you forget is the worst
    kind: the dump runs against the new binaries but the old artefacts stay on disk, so every answer that
    reads them is confidently describing code that has changed. Nothing reports it.

    Prints nothing unless the command actually looked like a build, because this fires after every Bash
    call and whatever it prints is context in the session for ever.
#>
$ErrorActionPreference = 'SilentlyContinue'

try {
    $raw = [Console]::In.ReadToEnd()
    if (-not $raw) { exit 0 }
    $payload = $raw | ConvertFrom-Json
}
catch { exit 0 }

$command = $null
if ($payload.tool_input) { $command = $payload.tool_input.command }
if (-not $command) { exit 0 }

# Narrow on purpose. UnrealBuildTool by name, the two build wrappers, and this plugin's own build
# script. A looser pattern would fire on every `dotnet test` and be noise.
$isBuild = $command -match '(?i)(UnrealBuildTool(\.exe)?|Build-UEAgentAccelerator\.ps1|\bBuild\.bat\b|\bRunUAT\b)'
if (-not $isBuild) { exit 0 }

# A dump in the same command means the pair was done properly and there is nothing to say.
if ($command -match '(?i)(Invoke-AgentMemoryDump|AgentMemoryDump|Update-MemoryStack)') { exit 0 }

Write-Output ("A build just ran. The reflection artefacts under Docs/AgentMemory still describe the code as it " +
              "was before it: they are regenerated by a dump, not by a build. If the build changed reflected " +
              "classes, properties or Blueprint-visible functions, run /ue-memory-stack:update before trusting " +
              "an answer that came from them.")
exit 0
